twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_4_layout.html.twig']
    paths:
        'templates/themes/admin/custom': 'admin'
        'templates/themes/admin/default': 'admin'
        'templates/themes/front/custom': 'front'
        'templates/themes/front/default': 'front'
