vich_uploader:
    db_driver: orm
    mappings:
        article_image:
            uri_prefix: '%env(IMAGE_POST_PATH)%'
            upload_destination: '%kernel.project_dir%/public%env(IMAGE_POST_PATH)%'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
