version: '3.7'
services:
  mariadb:
    image: mariadb:10.5.8
    ports: ['3306:3306']
    volumes:
      - ./data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=azerty
      - MYSQL_DATABASE=blog
      - MYSQL_USER=root
      - MYSQL_PASSWORD=azerty
  php:
    build: ./docker/php
    ports: ['9000:9000']
    volumes:
      - .:/var/www:cached
      - ./docker/scripts/php:/scripts
  nginx:
    build: ./docker/nginx
    ports: ['80:80']
    volumes: ['.:/var/www:cached']
  phpmyadmin:
    image: phpmyadmin
    ports: ['8080:80']
    restart: always
    environment:
      PMA_HOST: mariadb
      PMA_USER: root
      PMA_PASSWORD: azerty
#  node:
#    build:
#      context: ./docker/node
#    working_dir: /var/www
#    command: yarn run dev
#    volumes:
#      - .:/var/www
#    ports:
#      - 3000:3000